AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ASL Interpreter AWS Backend Orchestration

Resources:
  # To be filled during implementation
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ASLInterpreterWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
