"""Typed exceptions for the NIMBUS AI pipeline.

Each exception maps to a PROTOCOLS.md §4.1 error code so the ERROR event
payload can be generated by catching the exception type.
"""


class PipelineError(Exception):
    code: str = "PIPELINE_ERROR"
    fallback: str | None = None


class SageMakerError(PipelineError):
    code = "SAGEMAKER_INFERENCE_FAILED"
    fallback = "[UNKNOWN_SIGN]"


class BedrockError(PipelineError):
    code = "BEDROCK_TIMEOUT"
    fallback = None  # caller substitutes raw gloss


class PollyError(PipelineError):
    code = "POLLY_FAILED"


class RekognitionError(PipelineError):
    code = "REKOGNITION_FAILED"
    fallback = "CALM"


class RateLimitExceeded(PipelineError):
    code = "BEDROCK_TIMEOUT"
    fallback = None


class TranslateError(PipelineError):
    code = "TRANSLATE_FAILED"
    fallback = None  # caller falls back to English text


class SchemaValidationError(PipelineError):
    code = "SCHEMA_INVALID"
