"""Shared NIMBUS ASL vocabulary, ontology metadata, and seed handshape priors."""

from __future__ import annotations

import argparse
import copy
import json
import pathlib
import re
from typing import Any

SPECIAL_TOKENS: list[str] = ["[PAD]", "[EOS]", "[UNKNOWN_SIGN]"]

VOCAB_GROUPS: dict[str, list[str]] = {
    "Courtesy": [
        "HELLO",
        "GOODBYE",
        "PLEASE",
        "THANK-YOU",
        "SORRY",
        "EXCUSE-ME",
    ],
    "PronounsAndDeixis": [
        "I",
        "ME",
        "YOU",
        "WE",
        "THEY",
        "HE",
        "SHE",
        "THIS",
        "THAT",
    ],
    "Questions": [
        "WHAT",
        "WHO",
        "WHERE",
        "WHEN",
        "WHY",
        "HOW",
        "WHICH",
    ],
    "ModalsAndGrammar": [
        "YES",
        "NO",
        "CAN",
        "CANNOT",
        "WILL",
        "SHOULD",
        "MUST",
    ],
    "Verbs": [
        "WANT",
        "NEED",
        "LIKE",
        "LOVE",
        "KNOW",
        "THINK",
        "GO",
        "COME",
        "GIVE",
        "TAKE",
        "SHOW",
        "TELL",
        "ASK",
        "ANSWER",
        "UNDERSTAND",
        "REPEAT",
        "SEE",
        "LOOK",
        "WATCH",
        "READ",
        "WRITE",
        "LEARN",
        "STUDY",
        "WORK",
        "PLAY",
        "MAKE",
        "FIND",
        "MEET",
        "HELP",
        "WAIT",
        "STAY",
        "OPEN",
        "CLOSE",
        "START",
        "FINISH",
        "STOP",
        "INTERPRET",
        "SIGN",
    ],
    "Descriptors": [
        "GOOD",
        "BAD",
        "MORE",
        "LESS",
        "BIG",
        "SMALL",
        "NEW",
        "OLD",
        "SAME",
        "DIFFERENT",
        "RIGHT",
        "WRONG",
        "FAST",
        "SLOW",
        "EASY",
        "HARD",
        "HOT",
        "COLD",
    ],
    "Time": [
        "TIME",
        "NOW",
        "TODAY",
        "TOMORROW",
        "YESTERDAY",
        "MORNING",
        "AFTERNOON",
        "NIGHT",
        "LATER",
        "BEFORE",
        "AFTER",
        "MINUTE",
        "HOUR",
        "DAY",
        "WEEK",
    ],
    "Places": [
        "HOME",
        "SCHOOL",
        "STORE",
        "HOSPITAL",
        "BATHROOM",
        "ROOM",
        "OFFICE",
        "CLASS",
        "TABLE",
        "DOOR",
        "MEETING",
    ],
    "People": [
        "MOTHER",
        "FATHER",
        "SISTER",
        "BROTHER",
        "FRIEND",
        "FAMILY",
        "DOCTOR",
        "TEACHER",
        "INTERPRETER",
    ],
    "ObjectsAndNeeds": [
        "WATER",
        "FOOD",
        "MONEY",
        "CAR",
        "BOOK",
        "PHONE",
        "COMPUTER",
        "PAPER",
        "PEN",
        "MEDICINE",
        "CAPTION",
    ],
    "StatesAndEmotions": [
        "HAPPY",
        "SAD",
        "ANGRY",
        "SCARED",
        "TIRED",
        "SICK",
        "FINE",
        "HUNGRY",
        "THIRSTY",
        "READY",
    ],
    "Numbers": [
        "ZERO",
        "ONE",
        "TWO",
        "THREE",
        "FOUR",
        "FIVE",
    ],
}

GLOSS_VOCAB: list[str] = SPECIAL_TOKENS + [
    token
    for tokens in VOCAB_GROUPS.values()
    for token in tokens
]

TOKEN_TO_INDEX: dict[str, int] = {token: idx for idx, token in enumerate(GLOSS_VOCAB)}
TOKEN_TO_CATEGORY: dict[str, str] = {
    token: "Special" for token in SPECIAL_TOKENS
} | {
    token: category
    for category, tokens in VOCAB_GROUPS.items()
    for token in tokens
}

TOKEN_ALIASES: dict[str, str] = {
    "THANK YOU": "THANK-YOU",
    "THANKYOU": "THANK-YOU",
    "GOOD BYE": "GOODBYE",
    "GOOD-BYE": "GOODBYE",
    "EXCUSE ME": "EXCUSE-ME",
    "EXCUSEME": "EXCUSE-ME",
    "RESTROOM": "BATHROOM",
    "MOM": "MOTHER",
    "MOMMY": "MOTHER",
    "DAD": "FATHER",
    "DADDY": "FATHER",
    "CELLPHONE": "PHONE",
    "CELL PHONE": "PHONE",
    "CELL-PHONE": "PHONE",
    "CAN'T": "CANNOT",
    "CANT": "CANNOT",
}

for token in GLOSS_VOCAB:
    if "-" in token:
        TOKEN_ALIASES.setdefault(token.replace("-", " "), token)
        TOKEN_ALIASES.setdefault(token.replace("-", ""), token)

if len(GLOSS_VOCAB) != len(set(GLOSS_VOCAB)):
    raise ValueError("Vocabulary contains duplicate tokens")
if not 100 <= len(GLOSS_VOCAB) <= 150:
    raise ValueError(f"Expected 100-150 tokens, found {len(GLOSS_VOCAB)}")


def canonicalize_gloss(raw_gloss: str) -> str:
    """Normalize external gloss labels into the committed MVP vocabulary."""
    token = raw_gloss.strip().upper()
    token = token.replace("_", "-").replace("/", "-")
    token = token.replace("’", "'").replace("`", "'")
    token = re.sub(r"\([^)]*\)", "", token)
    token = re.sub(r"\s+", "-", token)
    token = token.rstrip("+")
    token = token.strip("-")
    if not token:
        return "[UNKNOWN_SIGN]"

    alias_candidates = {
        token,
        token.replace("-", " "),
        token.replace("-", ""),
        token.replace("'", ""),
    }
    for candidate in alias_candidates:
        if candidate in TOKEN_ALIASES:
            return TOKEN_ALIASES[candidate]
        if candidate in TOKEN_TO_INDEX:
            return candidate

    return token if token in TOKEN_TO_INDEX else "[UNKNOWN_SIGN]"


HANDSHAPE_TEMPLATES: dict[str, dict[str, Any]] = {
    "control-token": {
        "profile_id": "control-token",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": None,
            "dominant_end": None,
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": [],
        "locations": [],
        "movements": [],
        "two_handed": False,
        "notes": "Non-lexical control token used only by the training pipeline.",
    },
    "greeting-salute": {
        "profile_id": "greeting-salute",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "lateral"],
        "locations": ["temple", "head-side"],
        "movements": ["short-salute-outward"],
        "two_handed": False,
        "notes": "Greeting-style open hand near the head.",
    },
    "farewell-wave": {
        "profile_id": "farewell-wave",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space", "head-side"],
        "movements": ["side-wave"],
        "two_handed": False,
        "notes": "Wave-like citation form used for farewells.",
    },
    "please-circle": {
        "profile_id": "please-circle",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["upper-chest"],
        "movements": ["circular-rub"],
        "two_handed": False,
        "notes": "Flat hand circling on the chest.",
    },
    "thank-you-forward": {
        "profile_id": "thank-you-forward",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["chin", "mouth"],
        "movements": ["forward-away-from-face"],
        "two_handed": False,
        "notes": "Open hand moving from the chin outward.",
    },
    "apology-fist-circle": {
        "profile_id": "apology-fist-circle",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-FIST",
            "dominant_end": "A-FIST",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["upper-chest"],
        "movements": ["circular-rub"],
        "two_handed": False,
        "notes": "Closed hand circling over the chest.",
    },
    "excuse-me-brush": {
        "profile_id": "excuse-me-brush",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["cheek", "neutral-space"],
        "movements": ["short-brush-away"],
        "two_handed": False,
        "notes": "One-hand attention getter / pardon-style brush.",
    },
    "point-self": {
        "profile_id": "point-self",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["upper-chest"],
        "movements": ["short-self-point"],
        "two_handed": False,
        "notes": "Index point directed at the signer.",
    },
    "point-forward": {
        "profile_id": "point-forward",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["forward-point"],
        "two_handed": False,
        "notes": "Index point directed toward an addressee.",
    },
    "inclusive-sweep": {
        "profile_id": "inclusive-sweep",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "neutral"],
        "locations": ["chest-line", "neutral-space"],
        "movements": ["sweeping-arc"],
        "two_handed": False,
        "notes": "Inclusive arc or plural point sweep across space.",
    },
    "lateral-point": {
        "profile_id": "lateral-point",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["neutral-space", "person-locus"],
        "movements": ["short-lateral-point"],
        "two_handed": False,
        "notes": "Lateral point to a discourse referent or nearby object.",
    },
    "open-question": {
        "profile_id": "open-question",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["small-side-turn", "question-hold"],
        "two_handed": False,
        "notes": "General open-palm interrogative pattern.",
    },
    "chin-query": {
        "profile_id": "chin-query",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "upward"],
        "locations": ["chin"],
        "movements": ["small-tap", "question-hold"],
        "two_handed": False,
        "notes": "Query anchored at the chin area.",
    },
    "index-search": {
        "profile_id": "index-search",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "lateral"],
        "locations": ["neutral-space"],
        "movements": ["short-search-sweep"],
        "two_handed": False,
        "notes": "Index sweep through space, useful for location queries.",
    },
    "forehead-pull": {
        "profile_id": "forehead-pull",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "R",
            "dominant_end": "Y",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "lateral"],
        "locations": ["forehead"],
        "movements": ["outward-flick"],
        "two_handed": False,
        "notes": "Forehead-origin interrogative with outward release.",
    },
    "bent-hands-turn": {
        "profile_id": "bent-hands-turn",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "BENT-B",
            "dominant_end": "BENT-B",
            "non_dominant_start": "BENT-B",
            "non_dominant_end": "BENT-B",
        },
        "palm_orientations": ["upward", "inward"],
        "locations": ["neutral-space"],
        "movements": ["paired-rotation"],
        "two_handed": True,
        "notes": "Two bent hands rotating against each other.",
    },
    "two-way-contrast": {
        "profile_id": "two-way-contrast",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["alternating-point"],
        "two_handed": True,
        "notes": "Contrastive index points, useful for WHICH-like alternation.",
    },
    "fist-nod": {
        "profile_id": "fist-nod",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "S-FIST",
            "dominant_end": "S-FIST",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["neutral-space"],
        "movements": ["short-nod-like-bob"],
        "two_handed": False,
        "notes": "Closed fist bobbing motion for affirmation.",
    },
    "pinch-no": {
        "profile_id": "pinch-no",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "O",
            "dominant_end": "FLAT-O",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["pinch-close"],
        "two_handed": False,
        "notes": "Thumb and fingers closing together for negation.",
    },
    "fists-down": {
        "profile_id": "fists-down",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "S-FIST",
            "dominant_end": "S-FIST",
            "non_dominant_start": "S-FIST",
            "non_dominant_end": "S-FIST",
        },
        "palm_orientations": ["inward", "downward"],
        "locations": ["neutral-space"],
        "movements": ["paired-down-drop"],
        "two_handed": True,
        "notes": "Two closed hands dropping slightly together.",
    },
    "b-stop": {
        "profile_id": "b-stop",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["abrupt-stop"],
        "two_handed": True,
        "notes": "Open-hand stop or blocked path gesture.",
    },
    "index-future": {
        "profile_id": "index-future",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["cheek", "neutral-space"],
        "movements": ["forward-arc"],
        "two_handed": False,
        "notes": "Forward-oriented index movement, useful for future modality.",
    },
    "directive-point": {
        "profile_id": "directive-point",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["firm-forward-point"],
        "two_handed": False,
        "notes": "Firm directive point used for obligation or recommendation.",
    },
    "flat-palm-insist": {
        "profile_id": "flat-palm-insist",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["firm-down-press"],
        "two_handed": False,
        "notes": "Insistent downward press for strong obligation.",
    },
    "claw-chest": {
        "profile_id": "claw-chest",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "CLAW-5",
            "dominant_end": "CLAW-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["upper-chest"],
        "movements": ["draw-toward-body"],
        "two_handed": False,
        "notes": "Desire or need-like pull toward the body.",
    },
    "flat-palm-chest": {
        "profile_id": "flat-palm-chest",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["heart", "upper-chest"],
        "movements": ["tap", "rest"],
        "two_handed": False,
        "notes": "Chest-anchored preference or affection pattern.",
    },
    "forehead-touch": {
        "profile_id": "forehead-touch",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward", "lateral"],
        "locations": ["forehead", "temple"],
        "movements": ["tap", "release"],
        "two_handed": False,
        "notes": "Forehead/temple contact for cognition verbs.",
    },
    "directional-travel": {
        "profile_id": "directional-travel",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "neutral"],
        "locations": ["neutral-space"],
        "movements": ["path-directional"],
        "two_handed": False,
        "notes": "Directional travel or path movement through neutral space.",
    },
    "outward-transfer": {
        "profile_id": "outward-transfer",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "upward"],
        "locations": ["neutral-space"],
        "movements": ["forward-release"],
        "two_handed": False,
        "notes": "Information or object transfer away from the body.",
    },
    "inward-transfer": {
        "profile_id": "inward-transfer",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "FLAT-O",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward", "upward"],
        "locations": ["neutral-space", "torso"],
        "movements": ["draw-inward"],
        "two_handed": False,
        "notes": "Inward receiving or taking motion.",
    },
    "ask-hook": {
        "profile_id": "ask-hook",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "X",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["hook-forward"],
        "two_handed": False,
        "notes": "Question/request hook moving toward the addressee.",
    },
    "answer-down": {
        "profile_id": "answer-down",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["resolved-drop"],
        "two_handed": False,
        "notes": "Response-style downward resolution.",
    },
    "know-flip": {
        "profile_id": "know-flip",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["forehead", "neutral-space"],
        "movements": ["outward-open"],
        "two_handed": False,
        "notes": "Comprehension / realization release from the head.",
    },
    "repeat-cycle": {
        "profile_id": "repeat-cycle",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward", "neutral"],
        "locations": ["neutral-space"],
        "movements": ["small-circular-repeat"],
        "two_handed": False,
        "notes": "Short repeated loop or cycle.",
    },
    "vision-gaze": {
        "profile_id": "vision-gaze",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "V",
            "dominant_end": "V",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "lateral"],
        "locations": ["eyes", "neutral-space"],
        "movements": ["directed-gaze"],
        "two_handed": False,
        "notes": "Eye-to-target visual attention pattern.",
    },
    "read-page": {
        "profile_id": "read-page",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "V",
            "dominant_end": "V",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward", "inward"],
        "locations": ["nondominant-palm", "neutral-space"],
        "movements": ["scan-across-palm"],
        "two_handed": True,
        "notes": "Reading or tracking along a page-like surface.",
    },
    "write-surface": {
        "profile_id": "write-surface",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["nondominant-palm", "tabletop"],
        "movements": ["small-writing-strokes"],
        "two_handed": True,
        "notes": "Writing motion over a stable surface.",
    },
    "learn-from-palm": {
        "profile_id": "learn-from-palm",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["upward", "inward"],
        "locations": ["nondominant-palm", "forehead"],
        "movements": ["lift-to-head"],
        "two_handed": True,
        "notes": "Information lifted from the non-dominant hand to the head.",
    },
    "fists-tap": {
        "profile_id": "fists-tap",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "S-FIST",
            "dominant_end": "S-FIST",
            "non_dominant_start": "S-FIST",
            "non_dominant_end": "S-FIST",
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["paired-tap"],
        "two_handed": True,
        "notes": "Two-fist contact pattern used for work-like semantics.",
    },
    "y-twist": {
        "profile_id": "y-twist",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "Y",
            "dominant_end": "Y",
            "non_dominant_start": "Y",
            "non_dominant_end": "Y",
        },
        "palm_orientations": ["inward", "lateral"],
        "locations": ["neutral-space"],
        "movements": ["alternating-twist"],
        "two_handed": True,
        "notes": "Relaxed Y-hands twisting in opposite directions.",
    },
    "fists-twist": {
        "profile_id": "fists-twist",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "S-FIST",
            "dominant_end": "S-FIST",
            "non_dominant_start": "S-FIST",
            "non_dominant_end": "S-FIST",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["paired-rotation"],
        "two_handed": True,
        "notes": "Two closed hands twisting as if assembling or creating.",
    },
    "search-stop": {
        "profile_id": "search-stop",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "F",
            "dominant_end": "F",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["sweep-then-stop"],
        "two_handed": False,
        "notes": "Scanning motion resolving into a fixed location.",
    },
    "meet-converge": {
        "profile_id": "meet-converge",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["move-together"],
        "two_handed": True,
        "notes": "Two referents converging at the center.",
    },
    "support-up": {
        "profile_id": "support-up",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-FIST",
            "dominant_end": "A-FIST",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["upward"],
        "locations": ["nondominant-palm", "neutral-space"],
        "movements": ["lift-up"],
        "two_handed": True,
        "notes": "Dominant fist supported by the non-dominant hand.",
    },
    "wait-hold": {
        "profile_id": "wait-hold",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["hold", "subtle-tap"],
        "two_handed": False,
        "notes": "Minimal-movement hold used for waiting or pausing.",
    },
    "open-spread": {
        "profile_id": "open-spread",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "neutral"],
        "locations": ["neutral-space"],
        "movements": ["open-apart"],
        "two_handed": False,
        "notes": "Compact handshape opening outward.",
    },
    "close-shut": {
        "profile_id": "close-shut",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "FLAT-O",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward", "neutral"],
        "locations": ["neutral-space"],
        "movements": ["close-together"],
        "two_handed": False,
        "notes": "Open hand closing into a tighter configuration.",
    },
    "begin-lift": {
        "profile_id": "begin-lift",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["lift-and-open"],
        "two_handed": False,
        "notes": "Onset or activation pattern.",
    },
    "finish-flick": {
        "profile_id": "finish-flick",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "OPEN-5",
            "non_dominant_start": "FLAT-O",
            "non_dominant_end": "OPEN-5",
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["paired-outward-flick"],
        "two_handed": True,
        "notes": "Common completion-style outward release.",
    },
    "stop-block": {
        "profile_id": "stop-block",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["block-contact"],
        "two_handed": True,
        "notes": "Blocking or stopping contact between the hands.",
    },
    "interpret-bridge": {
        "profile_id": "interpret-bridge",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["inward", "outward"],
        "locations": ["mouth", "neutral-space"],
        "movements": ["alternating-transfer"],
        "two_handed": True,
        "notes": "Bidirectional language-transfer or interpretation bridge.",
    },
    "sign-hands": {
        "profile_id": "sign-hands",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space", "torso"],
        "movements": ["alternating-small-circles"],
        "two_handed": True,
        "notes": "Generic signing/communication motion.",
    },
    "good-palm": {
        "profile_id": "good-palm",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["chin", "neutral-space"],
        "movements": ["forward-drop"],
        "two_handed": False,
        "notes": "Positive evaluation moving out from the chin.",
    },
    "bad-flip": {
        "profile_id": "bad-flip",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "downward"],
        "locations": ["chin", "neutral-space"],
        "movements": ["flip-down"],
        "two_handed": False,
        "notes": "Open hand turning from positive to negative orientation.",
    },
    "more-tap": {
        "profile_id": "more-tap",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "FLAT-O",
            "non_dominant_start": "FLAT-O",
            "non_dominant_end": "FLAT-O",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["paired-tap-together"],
        "two_handed": True,
        "notes": "Both hands moving together for increase/addition.",
    },
    "less-drop": {
        "profile_id": "less-drop",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["downward-drop"],
        "two_handed": False,
        "notes": "Reduced quantity or downward-decrease motion.",
    },
    "size-large": {
        "profile_id": "size-large",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "CURVED-C",
            "dominant_end": "CURVED-C",
            "non_dominant_start": "CURVED-C",
            "non_dominant_end": "CURVED-C",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["expand-apart"],
        "two_handed": True,
        "notes": "Two curved hands showing large size or volume.",
    },
    "size-small": {
        "profile_id": "size-small",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "FLAT-O",
            "non_dominant_start": "FLAT-O",
            "non_dominant_end": "FLAT-O",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["hold-close"],
        "two_handed": True,
        "notes": "Two small-measure hands held close together.",
    },
    "new-flick": {
        "profile_id": "new-flick",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward", "outward"],
        "locations": ["nondominant-palm", "neutral-space"],
        "movements": ["peel-away"],
        "two_handed": False,
        "notes": "Newness as a fresh page or layer turning away.",
    },
    "old-arc": {
        "profile_id": "old-arc",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "L",
            "dominant_end": "L",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["chin", "jawline"],
        "movements": ["arc-to-cheek"],
        "two_handed": False,
        "notes": "Extended thumb/index arc near the cheek or jaw.",
    },
    "equal-index": {
        "profile_id": "equal-index",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["parallel-move"],
        "two_handed": True,
        "notes": "Parallel one-hand shapes to indicate sameness or alignment.",
    },
    "different-index": {
        "profile_id": "different-index",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["downward", "lateral"],
        "locations": ["neutral-space"],
        "movements": ["diverge-apart"],
        "two_handed": True,
        "notes": "Parallel hands diverging to mark difference.",
    },
    "thumbs-up": {
        "profile_id": "thumbs-up",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-FIST",
            "dominant_end": "A-FIST",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["firm-hold"],
        "two_handed": False,
        "notes": "Thumb-up evaluation or correctness marker.",
    },
    "wrong-y": {
        "profile_id": "wrong-y",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "Y",
            "dominant_end": "Y",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward", "lateral"],
        "locations": ["chin", "neutral-space"],
        "movements": ["outward-flick"],
        "two_handed": False,
        "notes": "Incorrectness or error marker with a quick release.",
    },
    "fast-snap": {
        "profile_id": "fast-snap",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["quick-snap-forward"],
        "two_handed": False,
        "notes": "Fast, sudden outward burst.",
    },
    "slow-brush": {
        "profile_id": "slow-brush",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["downward"],
        "locations": ["nondominant-index", "neutral-space"],
        "movements": ["draw-along-index"],
        "two_handed": True,
        "notes": "Dominant hand moving along a stable index path to show slowness.",
    },
    "easy-flick": {
        "profile_id": "easy-flick",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "OPEN-5",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "OPEN-5",
        },
        "palm_orientations": ["upward", "outward"],
        "locations": ["neutral-space"],
        "movements": ["paired-flick"],
        "two_handed": True,
        "notes": "Two hands flicking outward with little effort.",
    },
    "hard-knock": {
        "profile_id": "hard-knock",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-FIST",
            "dominant_end": "A-FIST",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["nondominant-palm", "neutral-space"],
        "movements": ["firm-contact"],
        "two_handed": True,
        "notes": "Hardness or difficulty via solid contact on a base hand.",
    },
    "hot-mouth": {
        "profile_id": "hot-mouth",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "CLAW-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["mouth"],
        "movements": ["wiggle-away"],
        "two_handed": False,
        "notes": "Heat moving away from the mouth or lower face.",
    },
    "cold-shiver": {
        "profile_id": "cold-shiver",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "S-FIST",
            "dominant_end": "S-FIST",
            "non_dominant_start": "S-FIST",
            "non_dominant_end": "S-FIST",
        },
        "palm_orientations": ["inward"],
        "locations": ["torso"],
        "movements": ["shiver"],
        "two_handed": True,
        "notes": "Closed hands trembling near the torso.",
    },
    "wrist-time": {
        "profile_id": "wrist-time",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "A-FIST",
            "non_dominant_end": "A-FIST",
        },
        "palm_orientations": ["downward"],
        "locations": ["wrist", "nondominant-wrist"],
        "movements": ["tap"],
        "two_handed": True,
        "notes": "Time reference by tapping or pointing to the wrist.",
    },
    "now-down": {
        "profile_id": "now-down",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "Y",
            "dominant_end": "Y",
            "non_dominant_start": "Y",
            "non_dominant_end": "Y",
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["paired-down-drop"],
        "two_handed": True,
        "notes": "Present-time marker with simultaneous downward movement.",
    },
    "day-drop": {
        "profile_id": "day-drop",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["outward", "downward"],
        "locations": ["neutral-space"],
        "movements": ["one-hand-over-other"],
        "two_handed": True,
        "notes": "Day-based temporal marker using one index over another.",
    },
    "tomorrow-forward": {
        "profile_id": "tomorrow-forward",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-HAND",
            "dominant_end": "A-HAND",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral", "outward"],
        "locations": ["cheek", "jawline"],
        "movements": ["forward-flick"],
        "two_handed": False,
        "notes": "Temporal deictic movement moving away from the cheek.",
    },
    "yesterday-back": {
        "profile_id": "yesterday-back",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-HAND",
            "dominant_end": "A-HAND",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral", "backward"],
        "locations": ["cheek", "jawline"],
        "movements": ["backward-flick"],
        "two_handed": False,
        "notes": "Temporal deictic movement moving backward from the cheek.",
    },
    "sunrise": {
        "profile_id": "sunrise",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "BENT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["upward"],
        "locations": ["nondominant-arm", "neutral-space"],
        "movements": ["rise-up"],
        "two_handed": True,
        "notes": "Sun rising above the horizon line.",
    },
    "sun-descent": {
        "profile_id": "sun-descent",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "BENT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["nondominant-arm", "neutral-space"],
        "movements": ["lower-down"],
        "two_handed": True,
        "notes": "Sun lowering toward the horizon line.",
    },
    "night-cover": {
        "profile_id": "night-cover",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["cover-over"],
        "two_handed": True,
        "notes": "Dominant hand covering over the non-dominant base to mark night.",
    },
    "later-shoulder": {
        "profile_id": "later-shoulder",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "L",
            "dominant_end": "L",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["backward", "lateral"],
        "locations": ["shoulder"],
        "movements": ["short-backward-hitch"],
        "two_handed": False,
        "notes": "Back-over-shoulder temporal displacement.",
    },
    "before-front": {
        "profile_id": "before-front",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["front-to-back-contrast"],
        "two_handed": True,
        "notes": "Front-positioned temporal relation.",
    },
    "after-back": {
        "profile_id": "after-back",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["backward"],
        "locations": ["neutral-space"],
        "movements": ["backward-placement"],
        "two_handed": True,
        "notes": "Back-positioned temporal relation.",
    },
    "minute-tap": {
        "profile_id": "minute-tap",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["contact-tap"],
        "two_handed": True,
        "notes": "Compact time-unit marker with brief contact.",
    },
    "hour-circle": {
        "profile_id": "hour-circle",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["upward", "inward"],
        "locations": ["neutral-space"],
        "movements": ["circular-over-base"],
        "two_handed": True,
        "notes": "Circular motion over a stable base hand.",
    },
    "week-over-palm": {
        "profile_id": "week-over-palm",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["nondominant-palm", "neutral-space"],
        "movements": ["sweep-over-palm"],
        "two_handed": True,
        "notes": "Week-style sweep of an index hand across the non-dominant palm.",
    },
    "home-cheek": {
        "profile_id": "home-cheek",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "FLAT-O",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["cheek", "mouth"],
        "movements": ["double-touch"],
        "two_handed": False,
        "notes": "Compact O hand touching the cheek or mouth side.",
    },
    "school-clap": {
        "profile_id": "school-clap",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["double-clap"],
        "two_handed": True,
        "notes": "Repeated flat-hand contact for school-like semantics.",
    },
    "store-shake": {
        "profile_id": "store-shake",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["small-side-shake"],
        "two_handed": False,
        "notes": "Open-hand marker associated with place/store semantics.",
    },
    "cross-arm": {
        "profile_id": "cross-arm",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "H",
            "dominant_end": "H",
            "non_dominant_start": "H",
            "non_dominant_end": "H",
        },
        "palm_orientations": ["downward"],
        "locations": ["upper-arm"],
        "movements": ["cross-touch"],
        "two_handed": True,
        "notes": "Cross or plus-like touch pattern anchored on the arm.",
    },
    "bathroom-t": {
        "profile_id": "bathroom-t",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "T",
            "dominant_end": "T",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["small-shake"],
        "two_handed": False,
        "notes": "T handshape associated with restroom/bathroom.",
    },
    "room-outline": {
        "profile_id": "room-outline",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "L",
            "dominant_end": "L",
            "non_dominant_start": "L",
            "non_dominant_end": "L",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["outline-square"],
        "two_handed": True,
        "notes": "Two L hands outlining a room-like boundary.",
    },
    "office-door": {
        "profile_id": "office-door",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "L",
            "dominant_end": "L",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["neutral-space"],
        "movements": ["hinge-open"],
        "two_handed": False,
        "notes": "Door or entry-like hinge movement.",
    },
    "class-group": {
        "profile_id": "class-group",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "CLAW-5",
            "dominant_end": "CLAW-5",
            "non_dominant_start": "CLAW-5",
            "non_dominant_end": "CLAW-5",
        },
        "palm_orientations": ["downward", "inward"],
        "locations": ["neutral-space"],
        "movements": ["grouping-toward-center"],
        "two_handed": True,
        "notes": "Grouped-claw classifier-style gathering motion.",
    },
    "table-flat": {
        "profile_id": "table-flat",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["neutral-space"],
        "movements": ["hold-flat"],
        "two_handed": False,
        "notes": "Flat stable surface classifier.",
    },
    "door-knock": {
        "profile_id": "door-knock",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["neutral-space"],
        "movements": ["hinge-swing"],
        "two_handed": False,
        "notes": "Hand rotating like a door opening on a hinge.",
    },
    "meeting-circle": {
        "profile_id": "meeting-circle",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["alternating-circle"],
        "two_handed": True,
        "notes": "Multiple participants moving in a shared circular space.",
    },
    "mother-thumb": {
        "profile_id": "mother-thumb",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "5-SPREAD-THUMB",
            "dominant_end": "5-SPREAD-THUMB",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["chin"],
        "movements": ["tap"],
        "two_handed": False,
        "notes": "Thumb-anchored kinship marker at the chin.",
    },
    "father-thumb": {
        "profile_id": "father-thumb",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "5-SPREAD-THUMB",
            "dominant_end": "5-SPREAD-THUMB",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["lateral"],
        "locations": ["forehead"],
        "movements": ["tap"],
        "two_handed": False,
        "notes": "Thumb-anchored kinship marker at the forehead.",
    },
    "sister-brother-l": {
        "profile_id": "sister-brother-l",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "L",
            "dominant_end": "L",
            "non_dominant_start": "INDEX-1",
            "non_dominant_end": "INDEX-1",
        },
        "palm_orientations": ["outward", "lateral"],
        "locations": ["chin-or-forehead", "neutral-space"],
        "movements": ["move-to-touch"],
        "two_handed": True,
        "notes": "Sibling relation built from a gender locus plus a linked referent.",
    },
    "friend-hooks": {
        "profile_id": "friend-hooks",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1-CROOKED",
            "dominant_end": "INDEX-1-CROOKED",
            "non_dominant_start": "INDEX-1-CROOKED",
            "non_dominant_end": "INDEX-1-CROOKED",
        },
        "palm_orientations": ["inward"],
        "locations": ["neutral-space"],
        "movements": ["hook-link"],
        "two_handed": True,
        "notes": "Two crooked index fingers hooking together.",
    },
    "family-f": {
        "profile_id": "family-f",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "F",
            "dominant_end": "F",
            "non_dominant_start": "F",
            "non_dominant_end": "F",
        },
        "palm_orientations": ["outward", "inward"],
        "locations": ["neutral-space"],
        "movements": ["circle-around-group"],
        "two_handed": True,
        "notes": "F handshapes circling to form a family/group boundary.",
    },
    "doctor-pulse": {
        "profile_id": "doctor-pulse",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "MIDDLE-2",
            "dominant_end": "MIDDLE-2",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["wrist"],
        "movements": ["pulse-tap"],
        "two_handed": False,
        "notes": "Pulse-check motion associated with DOCTOR.",
    },
    "teach-from-head": {
        "profile_id": "teach-from-head",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "OPEN-5",
            "non_dominant_start": "FLAT-O",
            "non_dominant_end": "OPEN-5",
        },
        "palm_orientations": ["outward"],
        "locations": ["forehead", "neutral-space"],
        "movements": ["release-from-head"],
        "two_handed": True,
        "notes": "Knowledge released from the head toward learners.",
    },
    "water-w": {
        "profile_id": "water-w",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "W",
            "dominant_end": "W",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward", "lateral"],
        "locations": ["chin"],
        "movements": ["tap"],
        "two_handed": False,
        "notes": "W handshape tapping near the chin.",
    },
    "food-mouth": {
        "profile_id": "food-mouth",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "FLAT-O",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward"],
        "locations": ["mouth"],
        "movements": ["tap"],
        "two_handed": False,
        "notes": "Compact closed fingertips tapping at the mouth.",
    },
    "money-flick": {
        "profile_id": "money-flick",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-O",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward"],
        "locations": ["nondominant-palm", "neutral-space"],
        "movements": ["flick-from-palm"],
        "two_handed": False,
        "notes": "Monetary transfer or coins/bills leaving the palm.",
    },
    "car-drive": {
        "profile_id": "car-drive",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "S-FIST",
            "dominant_end": "S-FIST",
            "non_dominant_start": "S-FIST",
            "non_dominant_end": "S-FIST",
        },
        "palm_orientations": ["inward"],
        "locations": ["torso"],
        "movements": ["steering-motion"],
        "two_handed": True,
        "notes": "Both hands holding and turning an invisible steering wheel.",
    },
    "book-open": {
        "profile_id": "book-open",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["upward"],
        "locations": ["neutral-space"],
        "movements": ["open-like-book"],
        "two_handed": True,
        "notes": "Closed book opening outward from the center.",
    },
    "phone-y": {
        "profile_id": "phone-y",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "Y",
            "dominant_end": "Y",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward", "lateral"],
        "locations": ["ear", "mouth"],
        "movements": ["tap-or-hold"],
        "two_handed": False,
        "notes": "Phone handshape held near the face.",
    },
    "type-keyboard": {
        "profile_id": "type-keyboard",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "CURVED-5",
            "dominant_end": "CURVED-5",
            "non_dominant_start": "CURVED-5",
            "non_dominant_end": "CURVED-5",
        },
        "palm_orientations": ["downward"],
        "locations": ["tabletop", "neutral-space"],
        "movements": ["alternating-tap"],
        "two_handed": True,
        "notes": "Typing-style rapid finger taps over a keyboard plane.",
    },
    "paper-flat": {
        "profile_id": "paper-flat",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FLAT-B",
            "dominant_end": "FLAT-B",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward", "downward"],
        "locations": ["neutral-space"],
        "movements": ["hold-flat"],
        "two_handed": False,
        "notes": "Stable flat surface representing a document or sheet.",
    },
    "medicine-spoon": {
        "profile_id": "medicine-spoon",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "M",
            "dominant_end": "M",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["upward"],
        "locations": ["mouth"],
        "movements": ["tap-or-scoop"],
        "two_handed": False,
        "notes": "Medication/ingestion motion near the mouth.",
    },
    "caption-line": {
        "profile_id": "caption-line",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": "FLAT-B",
            "non_dominant_end": "FLAT-B",
        },
        "palm_orientations": ["downward"],
        "locations": ["nondominant-palm", "screen-plane"],
        "movements": ["trace-line"],
        "two_handed": True,
        "notes": "Tracing text or caption lines across a flat plane.",
    },
    "happy-chest": {
        "profile_id": "happy-chest",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": "OPEN-5",
            "non_dominant_end": "OPEN-5",
        },
        "palm_orientations": ["inward"],
        "locations": ["upper-chest"],
        "movements": ["upward-brush"],
        "two_handed": True,
        "notes": "Open hands brushing upward on the chest.",
    },
    "sad-face-down": {
        "profile_id": "sad-face-down",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": "OPEN-5",
            "non_dominant_end": "OPEN-5",
        },
        "palm_orientations": ["downward"],
        "locations": ["face", "torso"],
        "movements": ["slide-down"],
        "two_handed": True,
        "notes": "Open hands sliding downward from the face.",
    },
    "angry-claw": {
        "profile_id": "angry-claw",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "CLAW-5",
            "dominant_end": "CLAW-5",
            "non_dominant_start": "CLAW-5",
            "non_dominant_end": "CLAW-5",
        },
        "palm_orientations": ["inward", "downward"],
        "locations": ["face", "torso"],
        "movements": ["claw-pull-down"],
        "two_handed": True,
        "notes": "Tense claw hands pulling downward.",
    },
    "scared-open": {
        "profile_id": "scared-open",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": "OPEN-5",
            "non_dominant_end": "OPEN-5",
        },
        "palm_orientations": ["outward"],
        "locations": ["upper-chest", "face"],
        "movements": ["burst-away"],
        "two_handed": True,
        "notes": "Fear / startle pattern moving away from the body.",
    },
    "tired-droop": {
        "profile_id": "tired-droop",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "MIDDLE-2",
            "dominant_end": "MIDDLE-2",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["downward"],
        "locations": ["eyes", "face"],
        "movements": ["droop-down"],
        "two_handed": False,
        "notes": "Tiredness anchored near the eyes or face.",
    },
    "sick-middle": {
        "profile_id": "sick-middle",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "MIDDLE-2",
            "dominant_end": "MIDDLE-2",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["forehead", "stomach"],
        "movements": ["alternating-touch"],
        "two_handed": False,
        "notes": "Middle-finger contact pattern for illness / sick.",
    },
    "fine-thumb": {
        "profile_id": "fine-thumb",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "A-FIST",
            "dominant_end": "A-FIST",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward", "upward"],
        "locations": ["upper-chest"],
        "movements": ["tap-or-lift"],
        "two_handed": False,
        "notes": "Thumb-up style fine / okay evaluation.",
    },
    "hungry-down": {
        "profile_id": "hungry-down",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "C",
            "dominant_end": "C",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["chest"],
        "movements": ["downward-slide"],
        "two_handed": False,
        "notes": "C hand sliding downward on the torso.",
    },
    "thirsty-throat": {
        "profile_id": "thirsty-throat",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["inward"],
        "locations": ["throat"],
        "movements": ["slide-down"],
        "two_handed": False,
        "notes": "Index finger sliding downward on the throat.",
    },
    "ready-r": {
        "profile_id": "ready-r",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "R",
            "dominant_end": "R",
            "non_dominant_start": "R",
            "non_dominant_end": "R",
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["paired-twist"],
        "two_handed": True,
        "notes": "R handshapes rotating slightly to mark readiness.",
    },
    "zero-o": {
        "profile_id": "zero-o",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "O",
            "dominant_end": "O",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["hold"],
        "two_handed": False,
        "notes": "Closed O handshape used for the numeral zero.",
    },
    "number-one": {
        "profile_id": "number-one",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "INDEX-1",
            "dominant_end": "INDEX-1",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["hold"],
        "two_handed": False,
        "notes": "Numeral one.",
    },
    "number-two": {
        "profile_id": "number-two",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "V",
            "dominant_end": "V",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["hold"],
        "two_handed": False,
        "notes": "Numeral two.",
    },
    "number-three": {
        "profile_id": "number-three",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "W",
            "dominant_end": "W",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["hold"],
        "two_handed": False,
        "notes": "Numeral three.",
    },
    "number-four": {
        "profile_id": "number-four",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "FOUR",
            "dominant_end": "FOUR",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["hold"],
        "two_handed": False,
        "notes": "Numeral four.",
    },
    "number-five": {
        "profile_id": "number-five",
        "source": "seed_mvp_template",
        "handshape_configurations": {
            "dominant_start": "OPEN-5",
            "dominant_end": "OPEN-5",
            "non_dominant_start": None,
            "non_dominant_end": None,
        },
        "palm_orientations": ["outward"],
        "locations": ["neutral-space"],
        "movements": ["hold"],
        "two_handed": False,
        "notes": "Numeral five.",
    },
}

TOKEN_TO_PROFILE: dict[str, str] = {
    "[PAD]": "control-token",
    "[EOS]": "control-token",
    "[UNKNOWN_SIGN]": "control-token",
    "HELLO": "greeting-salute",
    "GOODBYE": "farewell-wave",
    "PLEASE": "please-circle",
    "THANK-YOU": "thank-you-forward",
    "SORRY": "apology-fist-circle",
    "EXCUSE-ME": "excuse-me-brush",
    "I": "point-self",
    "ME": "point-self",
    "YOU": "point-forward",
    "WE": "inclusive-sweep",
    "THEY": "inclusive-sweep",
    "HE": "lateral-point",
    "SHE": "lateral-point",
    "THIS": "lateral-point",
    "THAT": "lateral-point",
    "WHAT": "open-question",
    "WHO": "chin-query",
    "WHERE": "index-search",
    "WHEN": "chin-query",
    "WHY": "forehead-pull",
    "HOW": "bent-hands-turn",
    "WHICH": "two-way-contrast",
    "YES": "fist-nod",
    "NO": "pinch-no",
    "CAN": "fists-down",
    "CANNOT": "b-stop",
    "WILL": "index-future",
    "SHOULD": "directive-point",
    "MUST": "flat-palm-insist",
    "WANT": "claw-chest",
    "NEED": "claw-chest",
    "LIKE": "flat-palm-chest",
    "LOVE": "flat-palm-chest",
    "KNOW": "forehead-touch",
    "THINK": "forehead-touch",
    "GO": "directional-travel",
    "COME": "directional-travel",
    "GIVE": "outward-transfer",
    "TAKE": "inward-transfer",
    "SHOW": "outward-transfer",
    "TELL": "outward-transfer",
    "ASK": "ask-hook",
    "ANSWER": "answer-down",
    "UNDERSTAND": "know-flip",
    "REPEAT": "repeat-cycle",
    "SEE": "vision-gaze",
    "LOOK": "vision-gaze",
    "WATCH": "vision-gaze",
    "READ": "read-page",
    "WRITE": "write-surface",
    "LEARN": "learn-from-palm",
    "STUDY": "learn-from-palm",
    "WORK": "fists-tap",
    "PLAY": "y-twist",
    "MAKE": "fists-twist",
    "FIND": "search-stop",
    "MEET": "meet-converge",
    "HELP": "support-up",
    "WAIT": "wait-hold",
    "STAY": "wait-hold",
    "OPEN": "open-spread",
    "CLOSE": "close-shut",
    "START": "begin-lift",
    "FINISH": "finish-flick",
    "STOP": "stop-block",
    "INTERPRET": "interpret-bridge",
    "SIGN": "sign-hands",
    "GOOD": "good-palm",
    "BAD": "bad-flip",
    "MORE": "more-tap",
    "LESS": "less-drop",
    "BIG": "size-large",
    "SMALL": "size-small",
    "NEW": "new-flick",
    "OLD": "old-arc",
    "SAME": "equal-index",
    "DIFFERENT": "different-index",
    "RIGHT": "thumbs-up",
    "WRONG": "wrong-y",
    "FAST": "fast-snap",
    "SLOW": "slow-brush",
    "EASY": "easy-flick",
    "HARD": "hard-knock",
    "HOT": "hot-mouth",
    "COLD": "cold-shiver",
    "TIME": "wrist-time",
    "NOW": "now-down",
    "TODAY": "day-drop",
    "TOMORROW": "tomorrow-forward",
    "YESTERDAY": "yesterday-back",
    "MORNING": "sunrise",
    "AFTERNOON": "sun-descent",
    "NIGHT": "night-cover",
    "LATER": "later-shoulder",
    "BEFORE": "before-front",
    "AFTER": "after-back",
    "MINUTE": "minute-tap",
    "HOUR": "hour-circle",
    "DAY": "day-drop",
    "WEEK": "week-over-palm",
    "HOME": "home-cheek",
    "SCHOOL": "school-clap",
    "STORE": "store-shake",
    "HOSPITAL": "cross-arm",
    "BATHROOM": "bathroom-t",
    "ROOM": "room-outline",
    "OFFICE": "office-door",
    "CLASS": "class-group",
    "TABLE": "table-flat",
    "DOOR": "door-knock",
    "MEETING": "meeting-circle",
    "MOTHER": "mother-thumb",
    "FATHER": "father-thumb",
    "SISTER": "sister-brother-l",
    "BROTHER": "sister-brother-l",
    "FRIEND": "friend-hooks",
    "FAMILY": "family-f",
    "DOCTOR": "doctor-pulse",
    "TEACHER": "teach-from-head",
    "INTERPRETER": "interpret-bridge",
    "WATER": "water-w",
    "FOOD": "food-mouth",
    "MONEY": "money-flick",
    "CAR": "car-drive",
    "BOOK": "book-open",
    "PHONE": "phone-y",
    "COMPUTER": "type-keyboard",
    "PAPER": "paper-flat",
    "PEN": "write-surface",
    "MEDICINE": "medicine-spoon",
    "CAPTION": "caption-line",
    "HAPPY": "happy-chest",
    "SAD": "sad-face-down",
    "ANGRY": "angry-claw",
    "SCARED": "scared-open",
    "TIRED": "tired-droop",
    "SICK": "sick-middle",
    "FINE": "fine-thumb",
    "HUNGRY": "hungry-down",
    "THIRSTY": "thirsty-throat",
    "READY": "ready-r",
    "ZERO": "zero-o",
    "ONE": "number-one",
    "TWO": "number-two",
    "THREE": "number-three",
    "FOUR": "number-four",
    "FIVE": "number-five",
}

TOKEN_OVERRIDES: dict[str, dict[str, Any]] = {
    "WE": {
        "locations": ["inclusive-space", "chest-line"],
        "movements": ["inclusive-arc"],
    },
    "THEY": {
        "locations": ["plural-loci", "neutral-space"],
        "movements": ["arc-across-multiple-loci"],
    },
    "HE": {
        "locations": ["person-locus-right", "neutral-space"],
    },
    "SHE": {
        "locations": ["person-locus-left", "neutral-space"],
    },
    "THIS": {
        "locations": ["proximal-space"],
        "movements": ["short-downward-point"],
    },
    "THAT": {
        "locations": ["distal-space"],
        "movements": ["extended-forward-point"],
    },
    "WHEN": {
        "locations": ["cheek", "temple", "neutral-space"],
        "movements": ["question-hold", "short-search-sweep"],
    },
    "DAY": {
        "locations": ["neutral-space", "sun-path"],
        "movements": ["horizontal-arc"],
    },
    "SISTER": {
        "locations": ["chin", "neutral-space"],
    },
    "BROTHER": {
        "locations": ["forehead", "neutral-space"],
    },
    "PEN": {
        "locations": ["handheld-space", "paper-surface"],
        "notes": "Pen or writing instrument; often pairs with a writing trajectory.",
    },
}


def build_gloss_to_handshape_map() -> dict[str, dict[str, Any]]:
    """Return the committed seed handshape prior for every gloss token."""
    missing = [token for token in GLOSS_VOCAB if token not in TOKEN_TO_PROFILE]
    if missing:
        raise ValueError(f"Missing handshape profiles for: {missing}")

    mapping: dict[str, dict[str, Any]] = {}
    for token in GLOSS_VOCAB:
        profile = copy.deepcopy(HANDSHAPE_TEMPLATES[TOKEN_TO_PROFILE[token]])
        profile["gloss"] = token
        profile["category"] = TOKEN_TO_CATEGORY[token]
        profile["token_index"] = TOKEN_TO_INDEX[token]
        if token in TOKEN_OVERRIDES:
            profile.update(copy.deepcopy(TOKEN_OVERRIDES[token]))
        mapping[token] = profile
    return mapping


def vocabulary_groups_payload() -> dict[str, Any]:
    return {
        "special_tokens": SPECIAL_TOKENS,
        "group_count": len(VOCAB_GROUPS),
        "token_count": len(GLOSS_VOCAB),
        "groups": [
            {
                "name": category,
                "count": len(tokens),
                "tokens": tokens,
            }
            for category, tokens in VOCAB_GROUPS.items()
        ],
    }


def write_vocabulary_assets(output_dir: str | pathlib.Path) -> dict[str, pathlib.Path]:
    output_path = pathlib.Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    paths = {
        "label_map": output_path / "label_map.json",
        "vocabulary_groups": output_path / "vocabulary_groups.json",
        "gloss_to_handshapes": output_path / "gloss_to_handshapes.json",
    }

    paths["label_map"].write_text(json.dumps(GLOSS_VOCAB, indent=2) + "\n", encoding="utf-8")
    paths["vocabulary_groups"].write_text(
        json.dumps(vocabulary_groups_payload(), indent=2) + "\n",
        encoding="utf-8",
    )
    paths["gloss_to_handshapes"].write_text(
        json.dumps(build_gloss_to_handshape_map(), indent=2) + "\n",
        encoding="utf-8",
    )
    return paths


def main() -> None:
    parser = argparse.ArgumentParser(description="Write shared NIMBUS vocabulary assets")
    parser.add_argument(
        "--output-dir",
        default=str(pathlib.Path(__file__).resolve().parent.parent / "data"),
        help="Directory where label_map.json, vocabulary_groups.json, and gloss_to_handshapes.json are written.",
    )
    args = parser.parse_args()
    write_vocabulary_assets(args.output_dir)


if __name__ == "__main__":
    main()
